### ISSUE TITLE
Merge IPv6 support

### ISSUE THREAD

**Issue by Bilge** [matsumotory/mod_extract_forwarded_for_2.4#1]
Hi, could you merge the IPv6 changes by Yoshfuji Hideaki @ http://tinyurl.com/dxk2c6/yoshfuji/extract_forwarded.git?

**Comment by matsumotory** [comment]
Hi, @BilgeXA ,
Thanks for your information. If you can send pull-request to me, I'll be happy to merge your pull-request.
